CREATE TABLE IF NOT EXISTS `countries` (
  `country_id` char(2) NOT NULL UNIQUE,
  `name` varchar(80) NOT NULL,
  `nicename` varchar(80) NOT NULL,
  `iso3` char(3),
  `continent_id` char(2) NOT NULL,
  `flag` char(29) NOT NULL,
  PRIMARY KEY (`country_id`), 
  FOREIGN KEY (`continent_id`) REFERENCES continents(`continent_id`) 
);

--
-- Dumping data for table `country`
--

INSERT INTO `countries` (`country_id`, `name`, `nicename`, `iso3`, `continents_id`, `flag`) VALUES
('AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 'AS', 'country_flags/png250px/af.png'),
('AL', 'ALBANIA', 'Albania', 'ALB', 'EU', 'country_flags/png250px/al.png'),
('DZ', 'ALGERIA', 'Algeria', 'DZA', 'AF', 'country_flags/png250px/dz.png'),
('AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 'OC', 'country_flags/png250px/as.png'),
('AD', 'ANDORRA', 'Andorra', 'AND', 'EU', 'country_flags/png250px/ad.png'),
('AO', 'ANGOLA', 'Angola', 'AGO', 'AF', 'country_flags/png250px/ao.png'),
('AI', 'ANGUILLA', 'Anguilla', 'AIA', 'NA', 'country_flags/png250px/ai.png'),
('AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 'NA', 'country_flags/png250px/ag.png'),
('AR', 'ARGENTINA', 'Argentina', 'ARG', 'SA', 'country_flags/png250px/ar.png'),
('AM', 'ARMENIA', 'Armenia', 'ARM', 'AS', 'country_flags/png250px/am.png'),
('AW', 'ARUBA', 'Aruba', 'ABW', 'NA', 'country_flags/png250px/aw.png'),
('AU', 'AUSTRALIA', 'Australia', 'AUS', 'OC', 'country_flags/png250px/au.png'),
('AT', 'AUSTRIA', 'Austria', 'AUT', 'EU', 'country_flags/png250px/at.png'),
('AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 'AS', 'country_flags/png250px/az.png'),
('BS', 'BAHAMAS', 'Bahamas', 'BHS', 'NA', 'country_flags/png250px/bs.png'),
('BH', 'BAHRAIN', 'Bahrain', 'BHR', 'AS', 'country_flags/png250px/bh.png'),
('BD', 'BANGLADESH', 'Bangladesh', 'BGD', 'AS', 'country_flags/png250px/bd.png'),
('BB', 'BARBADOS', 'Barbados', 'BRB', 'NA', 'country_flags/png250px/bb.png'),
('BY', 'BELARUS', 'Belarus', 'BLR', 'EU', 'country_flags/png250px/by.png'),
('BE', 'BELGIUM', 'Belgium', 'BEL', 'EU', 'country_flags/png250px/be.png'),
('BZ', 'BELIZE', 'Belize', 'BLZ', 'NA', 'country_flags/png250px/bz.png'),
('BJ', 'BENIN', 'Benin', 'BEN', 'AF', 'country_flags/png250px/bj.png'),
('BM', 'BERMUDA', 'Bermuda', 'BMU', 'NA', 'country_flags/png250px/bm.png'),
('BT', 'BHUTAN', 'Bhutan', 'BTN', 'AS', 'country_flags/png250px/bt.png'),
('BO', 'BOLIVIA', 'Bolivia', 'BOL', 'SA','country_flags/png250px/bo.png'),
('BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 'EU', 'country_flags/png250px/ba.png'),
('BW', 'BOTSWANA', 'Botswana', 'BWA', 'AF', 'country_flags/png250px/bw.png'),
('BR', 'BRAZIL', 'Brazil', 'BRA', 'SA', 'country_flags/png250px/br.png'),
('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', NULL, 'AS', 'country_flags/png250px/io.png'),
('BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 'AS', 'country_flags/png250px/bn.png'),
('BG', 'BULGARIA', 'Bulgaria', 'BGR', 'EU', 'country_flags/png250px/bg.png'),
('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 'AF', 'country_flags/png250px/bf.png'),
('BI', 'BURUNDI', 'Burundi', 'BDI', 'AF', 'country_flags/png250px/bi.png'),
('KH', 'CAMBODIA', 'Cambodia', 'KHM', 'AS', 'country_flags/png250px/kh.png'),
('CM', 'CAMEROON', 'Cameroon', 'CMR', 'AF', 'country_flags/png250px/cm.png'),
('CA', 'CANADA', 'Canada', 'CAN', 'NA', 'country_flags/png250px/ca.png'),
('CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 'AF', 'country_flags/png250px/cv.png'),
('KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 'NA', 'country_flags/png250px/ky.png'),
('CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 'AF', 'country_flags/png250px/cf.png'),
('TD', 'CHAD', 'Chad', 'TCD', 'AF', 'country_flags/png250px/td.png'),
('CL', 'CHILE', 'Chile', 'CHL', 'SA', 'country_flags/png250px/cl.png'),
('CN', 'CHINA', 'China', 'CHN', 'AS', 'country_flags/png250px/cn.png'),
('CX', 'CHRISTMAS ISLAND', 'Christmas Island', NULL, 'AS', 'country_flags/png250px/cx.png'),
('CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, 'AS', 'country_flags/png250px/cc.png'),
('CO', 'COLOMBIA', 'Colombia', 'COL', 'SA', 'country_flags/png250px/co.png'),
('KM', 'COMOROS', 'Comoros', 'COM', 'AF', 'country_flags/png250px/km.png'),
('CG', 'CONGO', 'Congo', 'COG', 'AF', 'country_flags/png250px/cg.png'),
('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', 'AF', 'country_flags/png250px/cd.png'),
('CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 'OC', 'country_flags/png250px/ck.png'),
('CR', 'COSTA RICA', 'Costa Rica', 'CRI', 'NA', 'country_flags/png250px/cr.png'),
('CI', 'COTE D''IVOIRE', 'Cote D''Ivoire', 'CIV', 'AF', 'country_flags/png250px/ci.png'),
('HR', 'CROATIA', 'Croatia', 'HRV', 'EU', 'country_flags/png250px/hr.png'),
('CU', 'CUBA', 'Cuba', 'CUB', 'NA', 'country_flags/png250px/cu.png'),
('CY', 'CYPRUS', 'Cyprus', 'CYP', 'AS', 'country_flags/png250px/cy.png'),
('CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', 'EU', 'country_flags/png250px/cz.png'),
('DK', 'DENMARK', 'Denmark', 'DNK', 'EU', 'country_flags/png250px/dk.png'),
('DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 'AF', 'country_flags/png250px/dj.png'),
('DM', 'DOMINICA', 'Dominica', 'DMA', 'NA', 'country_flags/png250px/dm.png'),
('DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 'NA', 'country_flags/png250px/do.png'),
('EC', 'ECUADOR', 'Ecuador', 'ECU', 'SA', 'country_flags/png250px/ec.png'),
('EG', 'EGYPT', 'Egypt', 'EGY', 'AF', 'country_flags/png250px/eg.png'),
('SV', 'EL SALVADOR', 'El Salvador', 'SLV', 'SA', 'country_flags/png250px/sv.png'),
('GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 'AF', 'country_flags/png250px/gq.png'),
('ER', 'ERITREA', 'Eritrea', 'ERI', 'AF', 'country_flags/png250px/er.png'),
('EE', 'ESTONIA', 'Estonia', 'EST', 'EU', 'country_flags/png250px/ee.png'),
('ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 'AF', 'country_flags/png250px/et.png'),
('FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 'SA', 'country_flags/png250px/fk.png'),
('FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', 'EU', 'country_flags/png250px/fo.png'),
('FJ', 'FIJI', 'Fiji', 'FJI', 'OC', 'country_flags/png250px/fj.png'),
('FI', 'FINLAND', 'Finland', 'FIN', 'EU', 'country_flags/png250px/fi.png'),
('FR', 'FRANCE', 'France', 'FRA', 'EU', 'country_flags/png250px/fr.png'),
('PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 'OC', 'country_flags/png250px/pf.png'),
('TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', NULL, 'AN', 'country_flags/png250px/tf.png'),
('GA', 'GABON', 'Gabon', 'GAB', 'AF', 'country_flags/png250px/ga.png'),
('GM', 'GAMBIA', 'Gambia', 'GMB', 'AF', 'country_flags/png250px/gm.png'),
('GE', 'GEORGIA', 'Georgia', 'GEO', 'AS', 'country_flags/png250px/ge.png'),
('DE', 'GERMANY', 'Germany', 'DEU', 'EU', 'country_flags/png250px/de.png'),
('GH', 'GHANA', 'Ghana', 'GHA', 'AF', 'country_flags/png250px/gh.png'),
('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 'EU', 'country_flags/png250px/gi.png'),
('GR', 'GREECE', 'Greece', 'GRC', 'EU', 'country_flags/png250px/gr.png'),
('GL', 'GREENLAND', 'Greenland', 'GRL', 'NA', 'country_flags/png250px/gl.png'),
('GD', 'GRENADA', 'Grenada', 'GRD', 'NA', 'country_flags/png250px/gd.png'),
('GU', 'GUAM', 'Guam', 'GUM', 'OC', 'country_flags/png250px/gu.png'),
('GT', 'GUATEMALA', 'Guatemala', 'GTM', 'NA', 'country_flags/png250px/gt.png'),
('GN', 'GUINEA', 'Guinea', 'GIN', 'AF', 'country_flags/png250px/gn.png'),
('GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 'AF', 'country_flags/png250px/gw.png'),
('GY', 'GUYANA', 'Guyana', 'GUY', 'SA', 'country_flags/png250px/gy.png'),
('HT', 'HAITI', 'Haiti', 'HTI', 'NA', 'country_flags/png250px/ht.png'),
('VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', 'EU', 'country_flags/png250px/va.png'),
('HN', 'HONDURAS', 'Honduras', 'HND', 'NA', 'country_flags/png250px/hn.png'),
('HK', 'HONG KONG', 'Hong Kong', 'HKG', 'AS', 'country_flags/png250px/hk.png'),
('HU', 'HUNGARY', 'Hungary', 'HUN', 'EU', 'country_flags/png250px/hu.png'),
('IS', 'ICELAND', 'Iceland', 'ISL', 'EU', 'country_flags/png250px/is.png'),
('IN', 'INDIA', 'India', 'IND', 'AS', 'country_flags/png250px/in.png'),
('ID', 'INDONESIA', 'Indonesia', 'IDN', 'AS', 'country_flags/png250px/id.png'),
('IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 'AS', 'country_flags/png250px/ir.png'),
('IQ', 'IRAQ', 'Iraq', 'IRQ', 'AS', 'country_flags/png250px/iq.png'),
('IE', 'IRELAND', 'Ireland', 'IRL', 'EU', 'country_flags/png250px/ie.png'),
('IL', 'ISRAEL', 'Israel', 'ISR', 'AS', 'country_flags/png250px/il.png'),
('IT', 'ITALY', 'Italy', 'ITA', 'EU', 'country_flags/png250px/it.png'),
('JM', 'JAMAICA', 'Jamaica', 'JAM', 'NA', 'country_flags/png250px/jm.png'),
('JP', 'JAPAN', 'Japan', 'JPN', 'AS', 'country_flags/png250px/jp.png'),
('JO', 'JORDAN', 'Jordan', 'JOR', 'AS', 'country_flags/png250px/jo.png'),
('KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 'AS', 'country_flags/png250px/kz.png'),
('KE', 'KENYA', 'Kenya', 'KEN', 'AF', 'country_flags/png250px/ke.png'),
('KI', 'KIRIBATI', 'Kiribati', 'KIR', 'OC', 'country_flags/png250px/ki.png'),
('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Korea, Democratic People''s Republic of', 'PRK', 'AS', 'country_flags/png250px/kp.png'),
('KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', 'AS', 'country_flags/png250px/kr.png'),
('KW', 'KUWAIT', 'Kuwait', 'KWT', 'AS', 'country_flags/png250px/kw.png'),
('KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 'AS', 'country_flags/png250px/kg.png'),
('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', 'AS', 'country_flags/png250px/la.png'),
('LV', 'LATVIA', 'Latvia', 'LVA', 'EU', 'country_flags/png250px/lv.png'),
('LB', 'LEBANON', 'Lebanon', 'LBN', 'AS', 'country_flags/png250px/lb.png'),
('LS', 'LESOTHO', 'Lesotho', 'LSO', 'AF', 'country_flags/png250px/ls.png'),
('LR', 'LIBERIA', 'Liberia', 'LBR', 'AF', 'country_flags/png250px/lr.png'),
('LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 'AF', 'country_flags/png250px/ly.png'),
('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 'EU', 'country_flags/png250px/li.png'),
('LT', 'LITHUANIA', 'Lithuania', 'LTU', 'EU', 'country_flags/png250px/lt.png'),
('LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 'EU', 'country_flags/png250px/lu.png'),
('MO', 'MACAO', 'Macao', 'MAC', 'AS', 'country_flags/png250px/mo.png'),
('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 'EU', 'country_flags/png250px/mk.png'),
('MG', 'MADAGASCAR', 'Madagascar', 'MDG', 'AF', 'country_flags/png250px/mg.png'),
('MW', 'MALAWI', 'Malawi', 'MWI', 'AF', 'country_flags/png250px/mw.png'),
('MY', 'MALAYSIA', 'Malaysia', 'MYS', 'AS', 'country_flags/png250px/my.png'),
('MV', 'MALDIVES', 'Maldives', 'MDV', 'AS', 'country_flags/png250px/mv.png'),
('ML', 'MALI', 'Mali', 'MLI', 'AF', 'country_flags/png250px/ml.png'),
('MT', 'MALTA', 'Malta', 'MLT', 'EU', 'country_flags/png250px/mt.png'),
('MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 'OC', 'country_flags/png250px/mh.png'),
('MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 'NA', 'country_flags/png250px/mq.png'),
('MR', 'MAURITANIA', 'Mauritania', 'MRT', 'AF', 'country_flags/png250px/mr.png'),
('MU', 'MAURITIUS', 'Mauritius', 'MUS', 'AF', 'country_flags/png250px/mu.png'),
('MX', 'MEXICO', 'Mexico', 'MEX', 'NA', 'country_flags/png250px/mx.png'),
('FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 'OC', 'country_flags/png250px/fm.png'),
('MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', 'EU', 'country_flags/png250px/md.png'),
('MC', 'MONACO', 'Monaco', 'MCO', 'EU', 'country_flags/png250px/mc.png'),
('MN', 'MONGOLIA', 'Mongolia', 'MNG', 'AS', 'country_flags/png250px/mn.png'),
('MS', 'MONTSERRAT', 'Montserrat', 'MSR', 'NA', 'country_flags/png250px/ms.png'),
('MA', 'MOROCCO', 'Morocco', 'MAR', 'AF', 'country_flags/png250px/ma.png'),
('MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 'AF', 'country_flags/png250px/mz.png'),
('MM', 'MYANMAR', 'Myanmar', 'MMR', 'AS', 'country_flags/png250px/mm.png'),
('NA', 'NAMIBIA', 'Namibia', 'NAM', 'AF', 'country_flags/png250px/na.png'),
('NR', 'NAURU', 'Nauru', 'NRU', 'OC', 'country_flags/png250px/nr.png'),
('NP', 'NEPAL', 'Nepal', 'NPL', 'AS', 'country_flags/png250px/np.png'),
('NL', 'NETHERLANDS', 'Netherlands', 'NLD', 'EU', 'country_flags/png250px/nl.png'),
('NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 'OC', 'country_flags/png250px/nc.png'),
('NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 'OC', 'country_flags/png250px/nz.png'),
('NI', 'NICARAGUA', 'Nicaragua', 'NIC', 'NA', 'country_flags/png250px/ni.png'),
('NE', 'NIGER', 'Niger', 'NER', 'AF', 'country_flags/png250px/ne.png'),
('NG', 'NIGERIA', 'Nigeria', 'NGA', 'AF', 'country_flags/png250px/ng.png'),
('NU', 'NIUE', 'Niue', 'NIU', 'OC', 'country_flags/png250px/nu.png'),
('NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 'OC', 'country_flags/png250px/nf.png'),
('MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 'OC', 'country_flags/png250px/mp.png'),
('NO', 'NORWAY', 'Norway', 'NOR', 'EU', 'country_flags/png250px/no.png'),
('OM', 'OMAN', 'Oman', 'OMN', 'AS', 'country_flags/png250px/om.png'),
('PK', 'PAKISTAN', 'Pakistan', 'PAK', 'AS', 'country_flags/png250px/pk.png'),
('PW', 'PALAU', 'Palau', 'PLW', 'OC', 'country_flags/png250px/pw.png'),
('PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL, 'AS', 'country_flags/png250px/ps.png'),
('PA', 'PANAMA', 'Panama', 'PAN', 'NA', 'country_flags/png250px/pa.png'),
('PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 'OC', 'country_flags/png250px/pg.png'),
('PY', 'PARAGUAY', 'Paraguay', 'PRY', 'SA', 'country_flags/png250px/py.png'),
('PE', 'PERU', 'Peru', 'PER', 'SA', 'country_flags/png250px/pe.png'),
('PH', 'PHILIPPINES', 'Philippines', 'PHL', 'AS', 'country_flags/png250px/ph.png'),
('PN', 'PITCAIRN', 'Pitcairn', 'PCN', 'OC', 'country_flags/png250px/pn.png'),
('PL', 'POLAND', 'Poland', 'POL', 'EU', 'country_flags/png250px/pl.png'),
('PT', 'PORTUGAL', 'Portugal', 'PRT', 'EU', 'country_flags/png250px/pt.png'),
('PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 'NA', 'country_flags/png250px/pr.png'),
('QA', 'QATAR', 'Qatar', 'QAT', 'AS', 'country_flags/png250px/qa.png'),
('RE', 'REUNION', 'Reunion', 'REU', 'AF', 'country_flags/png250px/re.png'),
('RO', 'ROMANIA', 'Romania', 'ROM', 'EU', 'country_flags/png250px/ro.png'),
('RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 'EU', 'country_flags/png250px/ru.png'),
('RW', 'RWANDA', 'Rwanda', 'RWA', 'AF', 'country_flags/png250px/rw.png'),
('SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 'AF', 'country_flags/png250px/sh.png'),
('KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 'NA', 'country_flags/png250px/kn.png'),
('LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 'NA', 'country_flags/png250px/lc.png'),
('VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 'NA', 'country_flags/png250px/vc.png'),
('WS', 'SAMOA', 'Samoa', 'WSM', 'OC', 'country_flags/png250px/ws.png'),
('SM', 'SAN MARINO', 'San Marino', 'SMR', 'EU', 'country_flags/png250px/sm.png'),
('ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 'AF', 'country_flags/png250px/st.png'),
('SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 'AS', 'country_flags/png250px/sa.png'),
('SN', 'SENEGAL', 'Senegal', 'SEN', 'AF', 'country_flags/png250px/sn.png'),
('SC', 'SEYCHELLES', 'Seychelles', 'SYC', 'AF', 'country_flags/png250px/sc.png'),
('SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 'AF', 'country_flags/png250px/sl.png'),
('SG', 'SINGAPORE', 'Singapore', 'SGP', 'AS', 'country_flags/png250px/sg.png'),
('SK', 'SLOVAKIA', 'Slovakia', 'SVK', 'EU', 'country_flags/png250px/sk.png'),
('SI', 'SLOVENIA', 'Slovenia', 'SVN', 'EU', 'country_flags/png250px/si.png'),
('SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 'OC', 'country_flags/png250px/sb.png'),
('SO', 'SOMALIA', 'Somalia', 'SOM', 'AF', 'country_flags/png250px/so.png'),
('ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 'AF', 'country_flags/png250px/za.png'),
('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', NULL, 'AN', 'country_flags/png250px/gs.png'),
('ES', 'SPAIN', 'Spain', 'ESP', 'EU', 'country_flags/png250px/es.png'),
('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 'AS', 'country_flags/png250px/lk.png'),
('SD', 'SUDAN', 'Sudan', 'SDN', 'AF', 'country_flags/png250px/sd.png'),
('SR', 'SURINAME', 'Suriname', 'SUR', 'SA', 'country_flags/png250px/sr.png'),
('SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 'AF', 'country_flags/png250px/sz.png'),
('SE', 'SWEDEN', 'Sweden', 'SWE', 'EU', 'country_flags/png250px/se.png'),
('CH', 'SWITZERLAND', 'Switzerland', 'CHE', 'EU', 'country_flags/png250px/ch.png'),
('SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 'AS', 'country_flags/png250px/sy.png'),
('TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', 'AS', 'country_flags/png250px/tw.png'),
('TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 'AS', 'country_flags/png250px/tj.png'),
('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', 'AF', 'country_flags/png250px/tz.png'),
('TH', 'THAILAND', 'Thailand', 'THA', 'AS', 'country_flags/png250px/th.png'),
('TL', 'TIMOR-LESTE', 'Timor-Leste', NULL, 'AS', 'country_flags/png250px/tl.png'),
('TG', 'TOGO', 'Togo', 'TGO', 'AF', 'country_flags/png250px/tg.png'),
('TK', 'TOKELAU', 'Tokelau', 'TKL', 'OC', 'country_flags/png250px/tk.png'),
('TO', 'TONGA', 'Tonga', 'TON', 'OC', 'country_flags/png250px/to.png'),
('TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 'NA', 'country_flags/png250px/tt.png'),
('TN', 'TUNISIA', 'Tunisia', 'TUN', 'AF', 'country_flags/png250px/tn.png'),
('TR', 'TURKEY', 'Turkey', 'TUR', 'AS', 'country_flags/png250px/tr.png'),
('TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 'AS', 'country_flags/png250px/tm.png'),
('TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 'NA', 'country_flags/png250px/tc.png'),
('TV', 'TUVALU', 'Tuvalu', 'TUV', 'OC', 'country_flags/png250px/tv.png'),
('UG', 'UGANDA', 'Uganda', 'UGA', 'AF', 'country_flags/png250px/ug.png'),
('UA', 'UKRAINE', 'Ukraine', 'UKR', 'EU', 'country_flags/png250px/ua.png'),
('AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 'AS', 'country_flags/png250px/ae.png'),
('GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', 'EU', 'country_flags/png250px/gb.png'),
('US', 'UNITED STATES', 'United States', 'USA', 'NA', 'country_flags/png250px/us.png'),
('UY', 'URUGUAY', 'Uruguay', 'URY', 'SA', 'country_flags/png250px/uy.png'),
('UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 'AS', 'country_flags/png250px/uz.png'),
('VU', 'VANUATU', 'Vanuatu', 'VUT', 'OC', 'country_flags/png250px/vu.png'),
('VE', 'VENEZUELA', 'Venezuela', 'VEN', 'SA', 'country_flags/png250px/ve.png'),
('VN', 'VIET NAM', 'Viet Nam', 'VNM', 'AS', 'country_flags/png250px/vn.png'),
('VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', 'NA', 'country_flags/png250px/vg.png'),
('VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.S.', 'VIR', 'NA', 'country_flags/png250px/vi.png'),
('YE', 'YEMEN', 'Yemen', 'YEM', 'AS', 'country_flags/png250px/ye.png'),
('ZM', 'ZAMBIA', 'Zambia', 'ZMB', 'AF', 'country_flags/png250px/zm.png'),
('ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 'AF', 'country_flags/png250px/zw.png'),
('RS', 'SERBIA', 'Serbia', 'SRB', 'EU', 'country_flags/png250px/rs.png'),
('ME', 'MONTENEGRO', 'Montenegro', 'MNE', 'EU', 'country_flags/png250px/me.png'),
('AX', 'ALAND ISLANDS', 'Aland Islands', 'ALA', 'EU', 'country_flags/png250px/ax.png'),
('GG', 'GUERNSEY', 'Guernsey', 'GGY', 'EU', 'country_flags/png250px/gg.png'),
('IM', 'ISLE OF MAN', 'Isle of Man', 'IMN', 'EU', 'country_flags/png250px/im.png'),
('JE', 'JERSEY', 'Jersey', 'JEY', 'EU', 'country_flags/png250px/je.png');
